FROM golang:1.25-alpine

RUN apk add --no-cache gcc musl-dev ca-certificates tzdata
RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

ENV TZ=Asia/Kuala_Lumpur
EXPOSE 8080

CMD ["air", "-c", ".air.docker.toml"]
